# Generated by Django 4.0.5 on 2023-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerais',
            name='secretário',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='gerais',
            name='servo_de_contas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
