# Generated by Django 4.0.5 on 2023-01-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_gerais_secretário_gerais_servo_de_contas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerais',
            name='saldo_Final_do_Extrato_Mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo da Conta Bancária no Fim do Mês'),
        ),
    ]
