# Generated by Django 4.0.5 on 2023-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_gerais_saldo_final_do_extrato_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerais',
            name='remessa_Enviada_para_Betel_Resolução',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Envio Fixo de Remessa para Betel '),
        ),
        migrations.AlterField(
            model_name='gerais',
            name='saldo_Final_da_Conta_Bancária_Mês_Anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo da Conta Bancária no Mês Anterior\t'),
        ),
        migrations.AlterField(
            model_name='gerais',
            name='saldo_Final_da_Conta_em_Betel_Mês_Anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo da Conta em Betel no Mês Anterior\t'),
        ),
        migrations.AlterField(
            model_name='gerais',
            name='saldo_Final_do_Extrato_de_Betel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo da Conta em Betel no Fim do Mês'),
        ),
        migrations.AlterField(
            model_name='gerais',
            name='saldo_Final_dos_Donativos_Mês_Anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Donativos Mês Anterior'),
        ),
    ]
