# Generated by Django 4.0.5 on 2023-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_contas_entrada_extra1_contas_entrada_extra2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='entrada_extra2',
            new_name='entrada_extra',
        ),
        migrations.RenameField(
            model_name='contas',
            old_name='entrada_extra1',
            new_name='entrada_extra_desc',
        ),
        migrations.RenameField(
            model_name='contas',
            old_name='saída_extra1',
            new_name='saída_extra',
        ),
        migrations.RenameField(
            model_name='contas',
            old_name='saída_extra2',
            new_name='saída_extra_desc',
        ),
    ]
