# Generated by Django 4.0.5 on 2023-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_rename_entrada_extra2_contas_entrada_extra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='fundo_reservado',
            new_name='fundos_reservados',
        ),
        migrations.AddField(
            model_name='contas',
            name='fundos_reservados_desc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='entrada_extra_desc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='saída_extra_desc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
