# Generated by Django 4.0.5 on 2023-01-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_rename_fundo_reservado_contas_fundos_reservados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='entrada_extra',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='entrada_extra_desc',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='fundos_reservados',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='fundos_reservados_desc',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='saída_extra',
        ),
        migrations.RemoveField(
            model_name='contas',
            name='saída_extra_desc',
        ),
    ]
